apiVersion: v2
name: env_dev
description: A Helm chart for env_dev
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ds-common
    version: "0.1.0"
    repository: file://../ds-common
  - name: config-server
    version: "0.1.0"
    repository: file://../services/config-server
  - name: os-inventory-service
    version: "0.1.0"
    repository: file://../services/os-inventory-service
  # - name: os-admin-dashboard
  #   version: "0.1.0"
  #   repository: file://../services/os-admin-dashboard


  - name: kafka-node1
    version: "0.1.0"
    repository: file://../services/kafka-node1
  - name: os-order-service
    version: "0.1.0"
    repository: file://../services/os-order-service
  # - name: os-notification-service
  #   version: "0.1.0"
  #   repository: file://../services/os-notification-service
  - name: os-ordering-ui
    version: "0.1.0"
    repository: file://../services/os-ordering-ui


  - name: rate-limiter-rules-dashboard
    version: "0.1.0"
    repository: file://../services/rate-limiter-rules-dashboard
  - name: keycloak
    version: "24.3.1"
    repository: file://../services/keycloak
  - name: rate-limiter-cache-node1
    version: "0.1.0"
    repository: file://../services/rate-limiter-cache-node1
  - name: rate-limiter-cache-node2
    version: "0.1.0"
    repository: file://../services/rate-limiter-cache-node2
  - name: api-gateway
    version: "0.1.0"
    repository: file://../services/api-gateway


  # - name: grafana
  #   version: "11.4.2"
  #   repository: file://../observability/grafana
  # - name: grafana-loki
  #   version: "4.7.1"
  #   repository: file://../observability/grafana-loki
  # - name: tempo
  #   version: "1.16.0"
  #   repository: file://../observability/tempo
  # - name: prometheus
  #   version: "26.0.1"
  #   repository: file://../observability/prometheus


  # - name: kvs-metadata-server-node0
  #   version: "0.1.0"
  #   repository: file://../services/kvs-metadata-server-node0
  # - name: kvs-storage-server-node1
  #   version: "0.1.0"
  #   repository: file://../services/kvs-storage-server-node1
  # - name: kvs-admin-dashboard
  #   version: "0.1.0"
  #   repository: file://../services/kvs-admin-dashboard
