debug: 'false'

#spring.config.import=configserver:http://localhost:8071/
spring:
  application:
    name: kvadminclient
  cloud:
    config:
      import-check:
        enabled: 'false'

server:
  port: '9207'
management:
  server:
    port: '9307'
    ssl:
      enabled: 'false'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
  endpoint:
    shutdown:
      enabled: 'true'
    health:
      probes:
        enabled: 'true'
      show-details: always
  health:
    liveness-state:
      enabled: 'true'
    readiness-state:
      enabled: 'true'
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: 'true'

logging:
  level:
    com:
      bteshome: INFO
    root: ERROR
    org:
      apache:
        ratis: INFO

client:
  client-id: 5a73f6ba-c728-4895-9acf-f20e919f0223

metadata:
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      #host: 0.0.0.0
      host: 127.0.0.1
      port: '9311'
    - id: '2'
      #host: 0.0.0.0
      host: 127.0.0.1
      port: '9312'
  num-partitions-default: 1
  num-partitions-min: 1
  num-partitions-max: 10
  replication-factor-default: 1

info:
  app:
    name: 'Key Value Store Admin Client'
    version: '1.0'
    description: 'Key Value Store Admin Client'
