debug: 'false'

#spring.config.import=configserver:http://localhost:8071/
spring:
  application:
    name: keyvaluestoreadminclient
  cloud:
    config:
      import-check:
        enabled: 'false'

management:
  server:
    port: '9507'
    ssl:
      enabled: 'false'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
  endpoint:
    shutdown:
      enabled: 'true'
    health:
      probes:
        enabled: 'true'
      show-details: always
  health:
    liveness-state:
      enabled: 'true'
    readiness-state:
      enabled: 'true'
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: 'true'

logging:
  level:
    com:
      bteshome: INFO
    root: ERROR
    org:
      apache:
        ratis: INFO

server:
  port: '9407'

admin-client:
  client-id: 8f6bec7a-694c-42a3-b3f1-a978f98ac2d9

metadata-server:
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      #host: 0.0.0.0
      host: 127.0.0.1
      port: '9311'

info:
  app:
    name: 'Key Value Store Admin Client'
    version: '1.0'
    description: 'Key Value Store Admin Client'
