server:
  port: '9320'

spring:
  application:
    name: keyvaluestore
  cloud:
    config:
      import-check:
        enabled: 'false'

metadata:
  node:
    id: '2'
    #host: 0.0.0.0
    #host: 127.0.0.1
    host: localhost
    port: '9312'
  peers:
    - id: ${metadata.node.id}
      host: ${metadata.node.host}
      port: ${metadata.node.port}
    - id: '1'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9311'
    - id: '3'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9313'
  storage-dir: /tmp/raft-server-2
  storage-node-heartbeat-expect-interval-ms: 10000
  storage-node-heartbeat-send-interval-ms: 5000
  storage-node-heartbeat-monitor-interval-ms: 5000
  storage-node-metadata-lag-threshold: 10
  storage-node-metadata-lag-ms: 1000000
  storage-node-replica-monitor-interval-ms: 3000
  storage-node-replica-lag-threshold: 3
  storage-node-replica-fetch-interval-ms: 500
  storage-node-replica-fetch-max-num-records: 1000
  ring-num-virtual-partitions: 3
  num-partitions-default: 1
  num-partitions-max: 10
  replication-factor-default: 1
  min-in-sync-replicas-default: 1
  write-timeout-ms: 30000
  wal-fetch-interval-ms: 100
  local-client-id: 0b3ad294-9e22-493b-a264-d4ea986bcc83

info:
  app:
    name: 'Key Value Store - Controller Node 2'
    version: '1.0'
    description: 'Key Value Store - Controller Node 2'

management:
  server:
    port: '9328'