server:
  port: '9320'

spring:
  application:
    name: keyvaluestore
  cloud:
    config:
      import-check:
        enabled: 'false'

metadata-server:
  node:
    id: '2'
    #host: 0.0.0.0
    host: 127.0.0.1
    port: '9312'
  peers:
    - id: ${metadata-server.node.id}
      host: ${metadata-server.node.host}
      port: ${metadata-server.node.port}
    - id: '1'
      #host: 0.0.0.0
      host: 127.0.0.1
      port: '9311'
  storage-dir: /tmp/raft-server-${node.id}

info:
  app:
    name: 'Key Value Store - Controller Node 2'
    version: '1.0'
    description: 'Key Value Store - Controller Node 2'

management:
  server:
    port: '9328'