server:
  port: '9310'

spring:
  application:
    name: keyvaluestore
  cloud:
    config:
      import-check:
        enabled: 'false'

metadata:
  node:
    id: '1'
    #host: 0.0.0.0
    #host: 127.0.0.1
    host: localhost
    port: '9311'
  peers:
    - id: ${metadata.node.id}
      host: ${metadata.node.host}
      port: ${metadata.node.port}
  storage-dir: /tmp/raft-server-1

info:
  app:
    name: 'Key Value Store - Controller Node 1'
    version: '1.0'
    description: 'Key Value Store - Controller Node 1'

management:
  server:
    port: '9318'