server:
  port: '9310'

metadata:
  node:
    id: '1'
    host: localhost
    port: '9311'
  peers:
    - id: ${metadata.node.id}
      host: ${metadata.node.host}
      port: ${metadata.node.port}
  storage-dir: /tmp/raft-server-0

info:
  app:
    name: 'Key Value Store Metadata Node'
    version: '1.0'
    description: 'Key Value Store Metadata Node'

management:
  server:
    port: '9318'