server:
  port: '9330'

spring:
  application:
    name: keyvaluestore
  cloud:
    config:
      import-check:
        enabled: 'false'

metadata:
  node:
    id: '3'
    #host: 0.0.0.0
    #host: 127.0.0.1
    host: localhost
    port: '9313'
  peers:
    - id: ${metadata.node.id}
      host: ${metadata.node.host}
      port: ${metadata.node.port}
    - id: '1'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9311'
    - id: '2'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9312'
  storage-dir: /tmp/raft-server-3
  storage-node-heartbeat-expect-interval-ms: 10000
  storage-node-heartbeat-send-interval-ms: 5000
  storage-node-heartbeat-monitor-interval-ms: 5000
  storage-node-metadata-refresh-interval-ms: 300000
  replica-monitor-interval-ms: 10000
  replica-lag-threshold-records: 4000
  replica-fetch-interval-ms: 500
  replica-fetch-max-num-records: 1000
  replica-end-offsets-snapshot-interval-ms: 10000
  num-partitions-default: 1
  num-partitions-max: 10
  replication-factor-default: 1
  min-in-sync-replicas-default: 1
  ring-num-virtual-partitions: 3
  write-timeout-ms: 30000
  local-client-id: 727694ec-72c8-4e98-abf0-4632b1d6ec6f

info:
  app:
    name: 'Key Value Store - Controller Node 3'
    version: '1.0'
    description: 'Key Value Store - Controller Node 3'

management:
  server:
    port: '9338'