package com.bteshome.keyvaluestore.common.requests;

public enum RequestType {
    METADATA_REFRESH,
    TABLE_CREATE,
    TABLE_GET,
    TABLE_LIST,
    STORAGE_NODE_JOIN,
    STORAGE_NODE_LEAVE,
    STORAGE_NODE_GET,
    STORAGE_NODE_LIST,
    STORAGE_NODE_HEARTBEAT,
    STORAGE_NODE_ACTIVATE,
    STORAGE_NODE_DEACTIVATE,
    REPLICA_REMOVE_FROM_ISR,
    UNKNOWN
}
