{{- if and .Values.autosharding.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stsdiscovery-{{ template "kube-entity-metrics.fullname" . }}
  namespace: {{ template "kube-entity-metrics.namespace" . }}
  labels:
    {{- include "kube-entity-metrics.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stsdiscovery-{{ template "kube-entity-metrics.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-entity-metrics.serviceAccountName" . }}
    namespace: {{ template "kube-entity-metrics.namespace" . }}
{{- end }}
