{{- if and .Values.autosharding.enabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stsdiscovery-{{ template "kube-entity-metrics.fullname" . }}
  namespace: {{ template "kube-entity-metrics.namespace" . }}
  labels:
    {{- include "kube-entity-metrics.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - {{ template "kube-entity-metrics.fullname" . }}
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
{{- end }}
