apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-node1
  labels:
    app: kafka-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-node1
  template:
    metadata:
      labels:
        app: kafka-node1
    spec:
      containers:
        - name: kafka-node1
          image: bitnami/kafka:3.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "250m"
          env:
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: 'MkU3OEVBNTcwNTJENDM2Qk'
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: '1@localhost:9093'
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-node1:9092
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
           