apiVersion: v2
name: os-ordering-ui-config
description: A Helm chart for os-ordering-ui-config
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ds-common
    version: "0.1.0"
    repository: file://../../ds-common
