server:
  port: '9607'

management:
  server:
    port: '9707'

metadata-client:
  client-id: 42af847f-4921-48bb-bec5-fb4898d0a6eb
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

storage:
  node:
    id: '2'
    host: localhost
    port: ${server.port}
    jmx-port: ${management.server.port}
    rack: ""
    storage-dir: storage-server-2
