server:
  port: '9807'

management:
  server:
    port: '9907'

metadata-client:
  client-id: 2ac5a91b-b439-4c52-9617-bdc4f3683c97
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

storage:
  node:
    id: '3'
    host: localhost
    port: ${server.port}
    jmx-port: ${management.server.port}
    rack: ""
    storage-dir: storage-server-3