spring:
  application:
    name: kvstorageserver

server:
  port: '9407'

management:
  server:
    port: '9507'

client:
  client-id: 15317a49-f8aa-4c0c-8753-1eebcfa68f23
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9311'
    - id: '2'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9312'
    - id: '3'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9313'
  metadata-refresh-interval-ms: 10000

storage:
  node:
    id: '0'
    #host: 0.0.0.0
    host: 127.0.0.1
    port: ${server.port}
    jmx-port: ${management.server.port}
    rack: ""
    #storage-dir: /tmp/storage-server-0
    storage-dir: storage-server-0


