server:
  port: '9407'

management:
  server:
    port: '9507'

storage:
  node:
    id: '1'
    host: localhost
    port: ${server.port}
    management-port: ${management.server.port}
    rack: ""
    storage-dir: storage-server-1

metadata-client:
  client-id: a30d2590-e197-46e1-826c-a51480786dfd
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '0'
      host: localhost
      port: '9310'
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

info:
  app:
    name: 'Key Value State Storage Server 1'
    version: '1.0'
    description: 'Key Value State Storage Server 1'