spring:
  application:
    name: kvstorageserver

server:
  port: '9407'

management:
  server:
    port: '9507'

client:
  client-id: 15317a49-f8aa-4c0c-8753-1eebcfa68f23

metadata:
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      #host: 0.0.0.0
      host: 127.0.0.1
      port: '9311'

storage:
  node:
    id: '0'
    #host: 0.0.0.0
    host: 127.0.0.1
    port: ${server.port}
    jmxPort: ${management.server.port}
    rack: ""
    storage-dir: /tmp/storage-server-0
  heartbeat-send-interval-seconds: 30

