spring:
  application:
    name: kvstorageserver2

server:
  port: '9807'

management:
  server:
    port: '9907'

client:
  client-id: 2ac5a91b-b439-4c52-9617-bdc4f3683c97
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9311'
    - id: '2'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9312'
    - id: '3'
      #host: 0.0.0.0
      #host: 127.0.0.1
      host: localhost
      port: '9313'
  metadata-refresh-interval-ms: 10000

storage:
  node:
    id: 'storage3'
    #host: 0.0.0.0
    host: 127.0.0.1
    port: ${server.port}
    jmx-port: ${management.server.port}
    rack: ""
    #storage-dir: /tmp/storage-server-3
    storage-dir: storage-server-3
