{{- define "ds-common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.image }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ . }}
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpuLimit }}
          env:
            {{- if .Values.appName }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.appName }}
            {{- end }}
            {{- if .Values.config_client_enabled }}
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server.default.svc.cluster.local:8071/
            {{- end }}
            {{- if .Values.TODO___otel_enabled }}
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/libs/opentelemetry-javaagent-2.10.0.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              #value: "http://dev-grafana-tempo-distributor:4317"
              #value: "http://dev-grafana-tempo-distributor:4318"
              #value: "http://dev-grafana-tempo-distributor:3200"
              #value: "http://dev-grafana-tempo-distributor:9095"
              #value: "http://dev-grafana-tempo-distributor:14268"
              #value: "http://dev-grafana-tempo-distributor:55680"
              #value: "http://dev-tempo:4317"
              value: "http://dev-tempo:4318"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.appName }}
            {{- end }}
            {{- if .Values.db_server_enabled }}
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: {{ .Values.dbName }}
            {{- end }}
            {{- if .Values.keycloak_enabled }}
            - name: KC_LOG_LEVEL
              value: debug
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_HOSTNAME
              value: "https://auth.bteshome.com"
            - name: KC_HOSTNAME_ADMIN
              value: "https://auth.bteshome.com"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_RESPONSE_HEADERS
              value: "Access-Control-Allow-Origin:order.bteshome.com;Access-Control-Allow-Methods:GET,POST,OPTIONS,PUT,DELETE;Access-Control-Allow-Headers:Authorization,Content-Type"
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY
              value: "/opt/keycloak/data/transaction-logs"
            {{- end }}
          {{- if .Values.pvc_enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.pvc_mountPath }}
          {{- end }}
      {{- if .Values.pvc_enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.serviceName }}
      {{- end }}
{{- end -}}