{{- define "ds-common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ . }}
            {{- end }}
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "250m"
          env:
            {{- if .Values.appName }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.appName }}
            {{- end }}
            {{- if .Values.config_client_enabled }}
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8071/
            {{- end }}
            {{- if .Values.TODO___otel_enabled }}
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/libs/opentelemetry-javaagent-2.10.0.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              #value: "http://dev-grafana-tempo-distributor:4317"
              #value: "http://dev-grafana-tempo-distributor:4318"
              #value: "http://dev-grafana-tempo-distributor:3200"
              #value: "http://dev-grafana-tempo-distributor:9095"
              #value: "http://dev-grafana-tempo-distributor:14268"
              #value: "http://dev-grafana-tempo-distributor:55680"
              #value: "http://dev-tempo:4317"
              value: "http://dev-tempo:4318"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.appName }}
            {{- end }}
            {{- if .Values.db_server_dbname }}
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: {{ .Values.db_server_dbname }}
            - name: MYSQL_USER
              value: ds
            - name: MYSQL_PASSWORD
              value: password
            {{- end }}
{{- end -}}