apiVersion: v2
name: keycloak-db
description: A Helm chart for keycloak-db
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ds-common
    version: "0.1.0"
    repository: file://../../../ds-common
