debug: 'false'

server:
  port: '83'

notification-disabled: false
inventory-service-url: http://localhost:82

management:
  server:
    port: '8308'
    ssl:
      enabled: 'false'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
  endpoint:
    shutdown:
      enabled: 'true'
    health:
      probes:
        enabled: 'true'
      show-details: always
  health:
    liveness-state:
      enabled: 'true'
    readiness-state:
      enabled: 'true'
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: 'true'

info:
  app:
    name: 'Order Service'
    version: '1.0'
    description: 'Order Service'

logging:
  level:
    com:
      bteshome: DEBUG
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

storage-client:
  endpoints: "localhost:9406,localhost:9506,localhost:9606"

spring:
  cloud:
    config:
      import-check:
        enabled: 'false'
    circuitbreaker:
      resilience4j:
        enabled: 'true'