serviceName: os-notification-service
appName: osnotificationservice

replicaCount: 1

image: bteshome/os-notification-service:latest

ports:
  - 9001
  - 9008

service:
  ports:
    - 9001
    - 9008

config_client_enabled: true
otel_enabled: true
