apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: bteshome/discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
            - containerPort: 8768
          env:
            - name: POD_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPRING_APPLICATION_NAME
              value: discoveryserver
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8071/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${POD_HOSTNAME}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://localhost:8761/eureka/

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: LoadBalancer
  ports:
    - name: main-port
      protocol: TCP
      port: 8761
      targetPort: 8761
    - name: actuator-port
      protocol: TCP
      port: 8768
      targetPort: 8768