apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: bteshome/inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 82
            - containerPort: 8208
          env:
            - name: SPRING_APPLICATION_NAME
              value: inventory
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8071/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: DB_HOST
              value: inventory-db
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/libs/opentelemetry-javaagent-2.10.0.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://t-grafana-tempo-distributor:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            #- name: OTEL_TRACES_EXPORTER
            #  value: "none"
            #- name: OTEL_LOGS_EXPORTER
            #  value: otlp
            - name: OTEL_SERVICE_NAME
              value: inventory

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  type: LoadBalancer
  ports:
    - name: main-port
      protocol: TCP
      port: 82
      targetPort: 82
    - name: actuator-port
      protocol: TCP
      port: 8208
      targetPort: 8208      