
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - port: 88
      name: keycloak
      targetPort: 88
  selector:
    app: keycloak
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      #hostname: keycloak1
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          imagePullPolicy: IfNotPresent
          args:
            - "start-dev"
          ports:
            - name: keycloak
              containerPort: 88
          env:
            - name: KC_DB
              value: mysql
            - name: KC_DB_USERNAME
              value: ds
            - name: KC_DB_PASSWORD
              value: password
            - name: KC_DB_URL
              value: jdbc:mysql://keycloak-db:3306/keycloak
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_LOG_LEVEL
              value: info
            - name: KC_REALM_NAME
              value: realm1
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            #- name: KC_HOSTNAME
            #  value: keycloak1
            - name: KC_HOSTNAME_PORT
              value: "88"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"

