apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: bteshome/notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
            - containerPort: 9008
          env:
            - name: SPRING_APPLICATION_NAME
              value: notification
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8071/
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              #value: "kafka:9092"
              value: kafka.default.svc.cluster.local:9092

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: LoadBalancer
  ports:
    - name: main-port
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: actuator-port
      protocol: TCP
      port: 9008
      targetPort: 9008      